language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - python3-pip
        - python3-pytest
script:
  - make -j$(nproc) DEBUG=1
    && ERROR=0
    && pushd Pal/src/host/Linux &>/dev/null
    && export LD_LIBRARY_PATH=${PWD}
    && popd &>/dev/null
    && pushd Pal/test &>/dev/null
    &&  make test || ERROR=1
    && popd &>/dev/null
    && pushd Pal/regression &>/dev/null
    &&  make regression || ERROR=1
    && popd &>/dev/null
    && [ $ERROR -eq 0 ] || false

matrix:
  include:
    - name: Build and test on x86_64
      os: linux
      arch: amd64
    - name: Build and test on ppc64
      os: linux
      arch: ppc64le
