language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - libssl-dev
        - ninja-build
        - protobuf-c-compiler
        - python3
        - python3-click
        - python3-jinja2
        - python3-lxml
        - python3-numpy
        - python3-pip
        - python3-scipy
        - python3-setuptools
        - python3-toml
script:
  - ls /sys/devices/system/node/ || true
  - cat /sys/devices/system/node/node*/cpulist || true
  - cat /sys/devices/system/node/node*/cpulist | od -tx1 || true
  - ./build.sh
    && sudo ninja -C build install &>build.log || tail -n 200 build.log
    && sudo pip3 install pytest
    && export INSTALL_DEPS=1
    && ./run_tests0
    && ./run_tests1
    && ./run_tests2

matrix:
  include:
    - name: Build and test on ppc64 focal
      os: linux
      arch: ppc64le
      dist: focal
      env: PYTHONVERSION=python3.8
      before_script:
        - python3 -m pip install 'meson>=0.55,<0.56'
