language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - meson
        - ninja-build
        - python3-pip
        - python3-pytest
script:
  - make -j$(nproc)
    && meson build -Ddirect=enabled
    && ninja -C build
    && sudo ninja -C build install
    && export PYTHONPATH=${PWD}/python
    && ERROR=0
    && pushd Pal/test &>/dev/null
    &&  make test || ERROR=1
    && popd &>/dev/null
    && pushd Pal/regression &>/dev/null
    &&  make regression || ERROR=1
    && popd &>/dev/null
    && [ $ERROR -eq 0 ] || false

matrix:
  include:
    - name: Build and test on x86_64
      os: linux
      arch: amd64
    - name: Build and test on ppc64
      os: linux
      arch: ppc64le
