language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - python3-pip
        - python3-pytest
        - python3.6
        - npm
        - node-gyp
        - nodejs-dev
        - libssl1.0-dev
script:
  - make -j$(nproc) DEBUG=1
    && ERROR=0
    && sudo apt-get -y update && sudo apt-get -y install python3-pip && sudo pip3 install --upgrade pytest
    && pushd Pal/test &>/dev/null
    && make test || ERROR=1
    && popd &>/dev/null
    && pushd Pal/regression &>/dev/null
    && make regression || ERROR=1
    && popd &>/dev/null
    && pushd LibOS/shim/test/fs &>/dev/null
    &&  make test || ERROR=1
    && popd &>/dev/null
    && pushd LibOS/shim/test/regression &>/dev/null
    &&  make regression || ERROR=1
    && popd &>/dev/null
    && pushd Examples/bash &>/dev/null
    &&  make regression || ERROR=1
    && popd &>/dev/null
    && pushd Examples/curl &>/dev/null
    &&  make check || ERROR=1
    && popd &>/dev/null
    && pushd Examples/nodejs &>/dev/null
    &&  sudo apt-get -y install nodejs
    &&  make check || echo "Flaky nodejs test failed"
    && popd &>/dev/null
    && pushd Examples/nodejs-express-server &>/dev/null
    &&  sudo apt-get -y install npm node-gyp nodejs-dev libssl1.0-dev
    &&  npm install express
    &&  make check
    && popd &>/dev/null
    && pushd Examples/python-simple &>/dev/null
    &&  sudo apt-get -y install python3.6
    &&  make check
    && popd &>/dev/null
    && [ $ERROR -eq 0 ] || false

matrix:
  include:
    - name: Build and test on x86_64
      os: linux
      arch: amd64
    - name: Build and test on ppc64
      os: linux
      arch: ppc64le
