language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - python3-pip
        - python3-pytest
script:
  - make -j$(nproc)
  - make -j$(nproc) test
  - ERROR=0
    && pushd Pal/src/host/Linux &>/dev/null
    && export LD_LIBRARY_PATH=${PWD}
    && popd &>/dev/null
    && pushd Pal/test &>/dev/null
    && _VERBOSE=1 ./run_tests.sh || ERROR=1
    && popd &>/dev/null
    && pushd Pal/regression &>/dev/null
    && _VERBOSE=1 ./run_tests.sh || ERROR=1
    && sudo apt-get -y update && sudo apt-get -y install python3-pip && sudo pip3 install --upgrade pytest && make pal-regression.xml || ERROR=1
    && popd &>/dev/null
    && pushd LibOS/shim/test/fs &>/dev/null
    &&  [ $(uname -m) = "ppc64le" ] && cp manifest.template-ppc64 manifest
    ;   rm -f fs-test.xml && make fs-test.xml || ERROR=1
    && popd &>/dev/null
    && pushd LibOS/shim/test/regression &>/dev/null
    &&  [ $(uname -m) = "ppc64le" ]
       && sudo mkdir -p /usr/lib64
       && for f in *template-ppc64; do cp $f ${f%%.template-ppc64}; done
    ;   rm -f libos-regression.xml && make libos-regression.xml || ERROR=1
    && popd &>/dev/null
    && [ $ERROR -eq 0 ] || false

matrix:
  include:
    - name: Build and test on x86_64
      os: linux
      arch: amd64
    - name: Build and test on ppc64
      os: linux
      arch: ppc64le
