language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - meson
        - ninja-build
        - python3-pip
        - python3-pytest
script:
  - make -j$(nproc)
    && ERROR=0
    && pushd Pal/test &>/dev/null
    && _VERBOSE=1 ./run_tests.sh || ERROR=1
    && popd &>/dev/null
    && pushd Pal/regression &>/dev/null
    && _VERBOSE=1 ./run_tests.sh || ERROR=1
    && sudo apt-get -y update && sudo apt-get -y install python3-pip && sudo pip3 install --upgrade pytest && make pal-regression.xml || ERROR=1
    && popd &>/dev/null
    && [ $ERROR -eq 0 ] || false

