language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - python3-pip
        - python3.6
        - npm
        - node-gyp
        - nodejs-dev
        - libssl1.0-dev
        - python3-click
        - python3-jinja2
        - python3-numpy
        - python3-scipy
        - python3-setuptools
        - python3-lxml
script:
  - make -j$(nproc)
    && sudo pip3 install pytest
    && export PYTHONVERSION=python3.6 INSTALL_DEPS=1
    && if [ ! -c /dev/kmsg ]; then sed -i "/devkmsg/d" LibOS/shim/test/regression/manifest.template; fi
    && ./run_tests0
    && ./run_tests1
    && ./run_tests2

matrix:
  include:
    - name: Build and test on ppc64
      os: linux
      arch: ppc64le
