language: c
dist: bionic
sudo: required
addons:
  apt:
      packages:
        - python3-pip
        - python3.6
        - npm
        - node-gyp
        - nodejs-dev
        - libssl1.0-dev
        - python3-numpy
        - python3-scipy
script:
  - make -j$(nproc)
    && sudo pip3 install pytest
    && ./run_tests.sh

matrix:
  include:
    - name: Build and test on x86_64
      os: linux
      arch: amd64
    - name: Build and test on ppc64
      os: linux
      arch: ppc64le
