#!/usr/bin/env bash

ARCH=$(uname -p)
[ "${ARCH}" == "ppc64le" ] && ARCH=ppc64

ERROR=0 \
    && pushd Pal/regression &>/dev/null \
    &&   TEST="Pal regresssion"; echo ">>>>>> $TEST <<<<<<"; RESULT="PASS" \
    &&   gramine-test pytest || { ERROR=1; RESULT="FAIL"; } \
    &&   echo ">>>>>> ${TEST}: $RESULT <<<<<" \
    && popd &>/dev/null \
    && pushd LibOS/shim/test/fs &>/dev/null \
    &&   TEST="shim fs test"; echo ">>>>>> $TEST <<<<<<"; RESULT="PASS" \
    &&   gramine-test pytest || { ERROR=1; RESULT="FAIL"; } \
    &&   echo ">>>>>> ${TEST}: $RESULT <<<<<" \
    && popd &>/dev/null \
    && pushd LibOS/shim/test/regression &>/dev/null \
    &&   TEST="shim regression"; echo ">>>>>> $TEST <<<<<<"; RESULT="PASS" \
    &&   gramine-test pytest || { ERROR=1; RESULT="FAIL"; } \
    &&   echo ">>>>>> ${TEST}: $RESULT <<<<<" \
    && popd &>/dev/null \
    && pushd LibOS/shim/test/abi/${ARCH} &>/dev/null \
    &&   TEST="shim abi"; echo ">>>>>> $TEST <<<<<<"; RESULT="PASS" \
    &&   gramine-test pytest || { ERROR=1; RESULT="FAIL"; } \
    &&   echo ">>>>>> ${TEST}: $RESULT <<<<<" \
    && popd &>/dev/null \
    && exit $ERROR
